name: Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel Deploy
        run: echo "Handled by Vercel Git Integration"